name: Mypy

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    name: Mypy
    steps:
    - uses: actions/checkout@v1
    - name: Set up Python 3.12
      uses: actions/setup-python@v1
      with:
        python-version: 3.12
    - name: Install Dependencies
      run: |
        pip install mypy types-requests types-python-dateutil
    - name: mypy
      run: |
        mypy --ignore-missing-imports --disallow-untyped-calls --disallow-untyped-defs --disallow-incomplete-defs ufcscraper
